---
title: "Counting Words"
author: "Ben Jacobs"
execute:
  keep-md: TRUE
  df-print: paged
  warning: false
format:
  html:
    theme: cerulean
    code-fold: true
    code-line-numbers: true
date: "2024-06-28" 
editor: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

pacman::p_load(tidyverse,stringi,dplyr,rio,readr,stringr)
```


# Comparison of Average Verse Length in the New Testament vs The Book of Mormon

```{r}
scriptures_data <- rio::import("http://scriptures.nephi.org/downloads/lds-scriptures.csv.zip") %>% 
  as_tibble()
```

```{r}
# Filter for the Book of Mormon
bom_text <- scriptures_data %>%
  filter(volume_title == "Book of Mormon")
```


```{r}
# View(scriptures_data)
```

```{r}
average_length_nt <- scriptures_data %>%
  filter(volume_title == "New Testament") %>%
  mutate(word_count = str_count(scripture_text, "\\w+")) %>%
  summarize(avg_length = mean(word_count)) %>%
  pull(avg_length)

average_length_bom <- scriptures_data %>%
  filter(volume_title == "Book of Mormon") %>%
  mutate(word_count = str_count(scripture_text, "\\w+")) %>%
  summarize(avg_length = mean(word_count)) %>%
  pull(avg_length)


print("Average Verse Length in the New Testament:")
average_length_nt
# --> 22.71

print("Average Verse Length in the Book of Mormon")
average_length_bom
# 40.51
```

# Number of Times "Jesus" is used in the New Testament Compared to The Book Of Mormon

```{r}
jesus_count_nt <- scriptures_data %>%
  filter(volume_title == "New Testament") %>%
  mutate(jesus_count = str_count(scripture_text, "\\bJesus\\b")) %>%
  pull(jesus_count) %>%
  sum()

# Count occurrences of "Jesus" in Book of Mormon
jesus_count_bom <- scriptures_data %>%
  filter(volume_title == "Book of Mormon") %>%
  mutate(jesus_count = str_count(scripture_text, "\\bJesus\\b")) %>%
  pull(jesus_count) %>%
  sum()

# Print the results
print(paste("Count of 'Jesus' in New Testament:", jesus_count_nt))
# --> 976
print(paste("Count of 'Jesus' in Book of Mormon:", jesus_count_bom))
# --> 184
```

# Average Word Count by Chapter in the Book of Mormon

```{r}
bom_text <- bom_text %>%
  mutate(verse_length = str_extract_all(scripture_text, "\\w+") %>%
                          lengths())

bom_chapters <- bom_text %>%
  group_by(book_title, chapter_number) %>%
  mutate(avg_verse_length_by_chapter = mean(verse_length)) %>%
  ungroup()

```

```{r}
ggplot(bom_chapters, aes(x = chapter_number, y = avg_verse_length_by_chapter, color = book_title)) +
  geom_point() +
  facet_wrap(~ book_title, scales = "free") + 
  geom_line(aes(group = chapter_number), alpha = 0.7) +  # Connect points by chapter within each facet
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Add smoothed line
  labs(title = "Average Verse Length Across Chapters in the Book of Mormon",
       x = "Chapter Number",
       y = "Average Verse Length (Number of Words)",
       color = "Book Title") +
  theme_bw()  
```


# Average Word Count by Verse in the Book of Mormon

```{r}
#View(bom_text)

bom_text <- bom_text %>%
  mutate(verse_length = str_extract_all(scripture_text, "\\w+") %>%
                          lengths())
                      

# Calculate verse count within each book_title
bom_text <- bom_text %>%
  group_by(book_title) %>%
  mutate(verse_count = row_number()) %>%
  ungroup()

```

```{r}
ggplot(bom_text, aes(x = verse_count, y = verse_length, color = book_title)) +
  geom_point() +
  facet_wrap(~ book_title, scales = "free") +  # Ensure scales are free for each facet
  geom_line() +
  geom_smooth(method = "loess", se = FALSE, color = "black") +
  labs(title = "Verse Length Across Verses in the Book of Mormon",
       x = "Verse Number",
       y = "Verse Length (Number of Words)",
       color = "Book Short Title") +
  theme_bw()
```


```{r}

library(ggplot2)
library(dplyr)

# Define sunset color palette
sunset_colors <- colorRampPalette(c("#FFD700", "#FFA500", "#FF6347", "#FF4477","#6622FF"))

# List of book titles to iterate over
book_titles <- unique(bom_text$book_title)

# Create a list to store plots
plots <- list()

# Iterate over each book title
for (title in book_titles) {
  
  # Filter data for current book title
  book_data <- filter(bom_text, book_title == title)
  
  # Plot for current book title
  plot <- ggplot(book_data, aes(x = verse_count, y = verse_length, color = book_title)) +
    geom_point(colour = sunset_colors(length(book_titles))[which(book_titles == title)]) +  # Use custom sunset color
    geom_smooth(method = "loess", se = FALSE, color = "black", alpha = 0.5) +
    labs(title = paste("Verse Length Across Verses in the Book of Mormon (", title, ")", sep = ""),
         x = "Verse Number",
         y = "Verse Length (Number of Words)",
         color = "Book Short Title") +
    theme_bw()
  
  # Store plot in the list
  plots[[title]] <- plot
}

# Display all plots (optional)
print(plots)

# Access individual plots by book title, e.g., plots$"1 Ne."


```

