---
title: "Distance Between Savior Names"
author: "Ben Jacobs"
execute:
  keep-md: TRUE
  df-print: paged
  warning: false
format:
  html:
    theme: cerulean
    code-fold: true
    code-line-numbers: true
date: "2024-06-28" 
editor: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

pacman::p_load(tidyverse,stringi,dplyr,rio,readr,stringr)
```




# Savior's Names Distances in the Book of Mormon

```{r}
download.file(url = "https://byuistats.github.io/M335/data/BoM_SaviorNames.rds", destfile = "BoM_SaviorNames.rds", mode = "wb")
savior_names <- read_rds("BoM_SaviorNames.rds") %>% as_tibble()

sav_names <- savior_names %>% pull(name) %>% str_c(collapse = "|")

```



```{r}
bom_data <- rio::import("http://scriptures.nephi.org/downloads/lds-scriptures.csv.zip") %>%
  as_tibble()

# Filter for the Book of Mormon
bom_text <- bom_data %>%
  filter(volume_title == "Book of Mormon") %>%
  select(book_short_title, scripture_text)

```



```{r}
# str_length(bom_text$scripture_text)
```

```{r}
# Calculate the number of words between occurrences of Savior names
dist_between <- bom_text %>%
  rowwise() %>%
  mutate(text_split = list(str_split(scripture_text, pattern = sav_names)[[1]])) %>%
  unnest(text_split) %>%
  mutate(word_count = str_count(text_split, "\\w+")) %>%
  filter(word_count > 0) %>%
  select(book_short_title, word_count) %>%
  rename(n.between = word_count)

```

```{r}
# Create the box plot
ggplot(dist_between, aes(y = book_short_title, x = n.between)) +
  scale_x_continuous(breaks = seq(0, max(dist_between$n.between), by = 10))+
  geom_boxplot(fill="skyblue") +
  labs(title = "Organized Distribution of Word Counts Between Savior Names by Book in the Book of Mormon",
       x = "Word Count Between Savior Names",
       y = "Book Short Title") +
  
  theme_bw()

```

```{r}
median_data <- dist_between %>%
  group_by(book_short_title) %>%
  summarize(median_n_between = median(n.between)) %>%
  arrange(desc(median_n_between)) %>%
  pull(book_short_title)

# Reorder book_short_title factor levels based on median n.between
dist_between$book_short_title <- factor(dist_between$book_short_title, levels = median_data)

# Create the box plot
ggplot(dist_between, aes(y = book_short_title, x = n.between)) +
  geom_boxplot(fill = "skyblue") +
  labs(title = "Distribution of Word Counts Between Savior Names by Book in the Book of Mormon",
       x = "Word Count Between Savior Names",
       y = "Book Short Title") +
  scale_x_continuous(breaks = seq(0, max(dist_between$n.between), by = 10)) +
  theme_bw()
```
