---
title: "Car Wash"
output: 
  html_document:
    keep_md: TRUE
date: "2024-06-05"
---

```{r}
# install.packages("riem")
```


```{r}
library(readr)
library(lubridate)
library(dplyr)
library(riem)
library(tidyverse)
```

```{r}
carwash <- read_csv("https://byuistats.github.io/M335/data/carwash.csv")
```


```{r}
View(carwash)
```

```{r}
carwash$fixedTime <- ymd_hms(carwash$time)
carwash <- carwash %>%
  mutate(hour = ceiling_date(fixedTime, unit = "hour")
)
```

```{r}
hourly_carwash <- carwash %>%
  mutate(hour = floor_date(fixedTime, unit = "hour")) %>%
  group_by(name, type, hour) %>%
  summarise(
    salesTotal = sum(amount, na.rm = TRUE),
    .groups = 'drop'  # To ungroup after summarising
  ) %>%
  select(name, type, hour, salesTotal)
```

```{r}
View(hourly_carwash)
```


```{r}
carwash <- carwash %>%
  mutate(hour = ceiling_date(fixedTime, unit = "hour")) %>%
  left_join(
    carwash %>%
      group_by(hour) %>%
      summarise(total_sales = sum(amount, na.rm = TRUE)),
    by = "hour"
  ) %>%
  rename(salesTotals = total_sales)
```

```{r}
earliest_date <- min(carwash$fixedTime, na.rm = TRUE)
latest_date <- max(carwash$fixedTime, na.rm = TRUE)

earliest_date
latest_date
```

```{r}
rextemps <- riem_measures(station = "RXE", date_start = "2016-05-13" , date_end = "2016-07-18")
```

```{r}
View(rextemps)
```

```{r}
rextemps <- rextemps %>%
  mutate(
    time = ymd_hms(valid, quiet = TRUE), # Use quiet=TRUE to suppress warnings
    hour = floor_date(time, unit = "hour")
  )
rextemps <- rextemps %>%
  mutate(hour = floor_date(time, unit = "hour"))

merged_data <- hourly_carwash %>%
  left_join(rextemps, by = "hour")
```

```{r}
View(merged_data)
```

```{r}
merged_data <- merged_data %>% arrange(hour)
merged_data <- merged_data %>%
  group_by(hour) %>%
  fill(tmpf, .direction = "downup") %>%
  ungroup()
```


```{r}
ggplot(merged_data, aes(x = hour, y = salesTotal, color = tmpf, shape = skyc1)) +
  geom_point(size = 3) +
  scale_color_gradient(name = "Temperature (°F)", low = "blue", high = "red") +
  labs(x = "Hour", y = "Sales Total") +
  theme_bw()
```



